version: '3.8'
services:
  redis:
    image: redis
    volumes:
      - ./data:/data
    container_name: redis
    
  web-app:
    image: aswines/ecommerc
    ports:
      - 80:3000
    volumes:
      - ./:/app  
    container_name: web-app
    depends_on:
      - redis
   