version: "3.8"
services:
  redis:
    image: redis
    volumes:
      - ./data:/data
    container_name: redis

  web-app:
    image: aswines/ecommerce
    # platform: linux/amd64
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    # volumes:
    #   - ./:/app
    container_name: web-app
    depends_on:
      - redis
